"""update pwdhash length

Revision ID: 92e579805056
Revises: 901d02b12793
Create Date: 2021-03-24 11:30:04.542923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92e579805056'
down_revision = '901d02b12793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'pwd_hash',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'pwd_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
