"""create table

Revision ID: de2a3b1abdd4
Revises: 
Create Date: 2021-03-23 21:56:41.434199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2a3b1abdd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adminId', sa.String(length=20), nullable=True),
    sa.Column('passWd', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=20), nullable=True),
    sa.Column('goodsId', sa.String(length=20), nullable=True),
    sa.Column('orderTime', sa.DateTime(), nullable=True),
    sa.Column('orderCount', sa.SmallInteger(), nullable=True),
    sa.Column('salePrice', sa.Float(), nullable=True),
    sa.Column('userChecked', sa.Boolean(), nullable=True),
    sa.Column('orderNumber', sa.String(length=50), nullable=True),
    sa.Column('postTime', sa.DateTime(), nullable=True),
    sa.Column('adminChecked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basket_orderTime'), 'basket', ['orderTime'], unique=False)
    op.create_index(op.f('ix_basket_postTime'), 'basket', ['postTime'], unique=False)
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typeid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('an_number', sa.String(length=50), nullable=True),
    sa.Column('producer', sa.String(length=20), nullable=True),
    sa.Column('package', sa.String(length=20), nullable=True),
    sa.Column('salePrice', sa.Float(), nullable=True),
    sa.Column('storePrice', sa.Float(), nullable=True),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.Column('readCount', sa.Integer(), nullable=True),
    sa.Column('buyCount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=20), nullable=True),
    sa.Column('pwd', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(length=1000), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('telephone', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('goods_type')
    op.drop_table('goods')
    op.drop_index(op.f('ix_basket_postTime'), table_name='basket')
    op.drop_index(op.f('ix_basket_orderTime'), table_name='basket')
    op.drop_table('basket')
    op.drop_table('admin')
    # ### end Alembic commands ###
